[build]
  command = "npm run build"
  publish = "dist/sms-client"

[context.production]
  command = "ng build --configuration=production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
